title: "Jaisree’s — Research"
description: "AI • Robotics • Systems — notes, papers, projects"
url: "https://jaisree25.github.io"
theme: minima

# Author info (string, not object → no hash dump)
author: "Jaisree David Ravikumar"
email: "your@email.com"

minima:
  skin: auto
  social_links:
    - { platform: github,   user_url: "https://github.com/jaisree25" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/jaisree25/" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=XXXX" }
    - { platform: orcid,    user_url: "https://orcid.org/XXXX-XXXX-XXXX-XXXX" }

collections:
  projects:
    output: true
    permalink: /projects/:name/
  publications:
    output: true
    permalink: /pubs/:name/
  competitions:
    output: true
    permalink: /competitions/:name/
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM

header_pages:
  - about.md
  - projects.md
  - publications.md
  - posts.md
  - competitions.md 
 
exclude:
  - README.md

logo: /assets/images/profile.webp

social:
  image: /assets/images/profile.webp
